# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: multi-agent-custom-automation-engine-solution-accelerator
metadata:
  template: multi-agent-custom-automation-engine-solution-accelerator@1.0
requiredVersions:
  azd: ">=1.15.0 !=1.17.1"

services:
  backend:
    project: ./src/backend
    language: py
    host: containerapp
    docker:
      image: backend
      remoteBuild: true
  
  mcp:
    project: ./src/mcp_server
    language: py
    host: containerapp
    docker:
      image: mcp
      remoteBuild: true

  frontend:
    project: ./src/frontend
    language: py
    host: appservice
    dist: ./dist
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: ../../infra/scripts/package_frontend.ps1
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run: bash ../../infra/scripts/package_frontend.sh
          interactive: true
          continueOnError: false

hooks:
  postdeploy:
    windows:
      run: |
        Write-Host "To upload Team Configurations to Cosmos. Run the following command in PowerShell:"
        Write-Host "infra\scripts\Upload-Team-Config.ps1" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "To index Sample Data into Azure Search. Run the following command in PowerShell:"
        Write-Host "infra\scripts\Process-Sample-Data.ps1" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "If you want to run both scripts as single command, you can use the following command in PowerShell:"
        Write-Host "infra\scripts\Team-Config-And-Data.ps1" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "You can access the deployed Frontend application at the following URL:"
        Write-Host "https://$env:webSiteDefaultHostname" -ForegroundColor Cyan
      shell: pwsh
      interactive: true
    posix:
      run: |
        Blue='\033[0;34m'
        NC='\033[0m'
        echo "To upload Team Configurations to Cosmos. Run the following command in Bash:"
        echo "${Blue}bash infra/scripts/upload_team_config.sh"
        echo ""
        echo "${NC}To index Sample Data into Azure Search. Run the following command in Bash:"
        echo "${Blue}bash infra/scripts/process_sample_data.sh"
        echo ""
        echo "${NC}If you want to run both scripts as single command, you can use the following command in Bash:"
        echo "${Blue}bash infra/scripts/team_config_and_data.sh"
        echo ""
        echo "${NC}You can access the deployed Frontend application at the following URL:"
        echo "${Blue}https://$webSiteDefaultHostname"
      shell: sh
      interactive: true